### ISSUE TITLE
Cargo Crate

### ISSUE THREAD

**Issue by theAkito** [dandyvica/dqy#1]
May this be released as a Cargo Crate, so we can install it via `cargo install dqy`?

I could also make a Pull Request for this, if welcome.

**Comment by dandyvica** [comment]
Hello, that's a good idea for the future. Still working on it for some additional bug fixes.

**Comment by fasttaps** [comment]
I am also waiting for this!

**Comment by eaves-dropper** [comment]
@dandyvica please upload this on crates.io, it is really simple... Here are the steps, if you need: (right now the name dqy is available)

## 1. Create a crates.io account

1. Go to **crates.io**
2. Sign in using **GitHub** (required)

---

## 2. Get your API token

1. On crates.io, open **Account Settings**
2. Generate a **New Token**
3. Copy it (you’ll only see it once)

Then log in from your terminal:

```bash
cargo login <YOUR_API_TOKEN>
```

This stores the token locally for future publishes.

---

## 3. Prepare your crate

If you don’t already have one:

```bash
cargo new my_crate_name
cd my_crate_name
```

Crate names must be:

* **unique**
* **lowercase**
* use `-` not `_`

---

## 4. Update `Cargo.toml` metadata (required)

Edit `Cargo.toml`:

```toml
[package]
name = "my_crate_name"
version = "0.1.0"
edition = "2021"
description = "A short description of what the crate does"
license = "MIT OR Apache-2.0"
repository = "https://github.com/yourname/my_crate_name"
readme = "README.md"
keywords = ["cli", "parser"]
categories = ["command-line-utilities"]
```

**Required fields**:

* `name`
* `version`
* `description`
* `license`

👉 Use an SPDX license identifier
👉 You must include a `LICENSE` file if you specify one

---

## 5. Add a README

Create `README.md` (this appears on crates.io):

````md
# my_crate_name

Brief explanation.

## Usage
```rust
use my_crate_name::*;
````

````

---

## 6. Check what will be published
Before publishing:
```bash
cargo publish --dry-run
````

This:

* validates metadata
* shows included files
* catches common mistakes

You can exclude files with `.gitignore` or:

```toml
exclude = ["tests/", "examples/"]
```

---

## 7. Publish the crate

When ready:

```bash
cargo publish
```

If successful:

* Your crate is live on **crates.io**
* Docs are built on **docs.rs**

---

## 8. Publishing updates (new versions)

You **cannot overwrite** a version. To update:

1. Bump the version:

```toml
version = "0.1.1"
```

2. Publish again:

```bash
cargo publish
```

Follow **semver**:

* `0.1.1` → bugfix
* `0.2.0` → breaking change
* `1.0.0` → stable API

---

## 9. Yank a broken release (optional)

If a version is bad but shouldn’t be deleted:

```bash
cargo yank --vers 0.1.0
```

This prevents new installs but doesn’t break existing users.

---

## 10. Verify

* Visit `https://crates.io/crates/my_crate_name`
* Check docs: `https://docs.rs/my_crate_name`

---

### Common pitfalls

* ❌ Missing `description` or `license`
* ❌ Crate name already taken
* ❌ Large files included unintentionally
* ❌ Forgetting to bump version before republish
